import { PrismaClient, ServiceFieldType } from '@prisma/client';

// ─── Indian States ────────────────────────────────────────────────────────────
const INDIAN_STATES_OPTIONS = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry"
];

// ─── PAN Category ─────────────────────────────────────────────────────────────
const PAN_TITLE_OPTIONS = ["Shri (Mr.)", "Smt. (Mrs.)", "Kumari (Miss)"];
const PAN_GENDER_OPTIONS = ["Male", "Female", "Transgender"];

export async function seedServiceFields(prisma: PrismaClient): Promise<number> {
  const fields = [
    // ──────────────────────────────────────────────────────────────────────────
        // ──────────────────────────────────────────────────────────────────────────
    // 1. New PAN Apply
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'new-pan-apply',
      label: 'Category of Applicant',
      fieldKey: 'applicantCategory',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Category',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { options: ['Individual'] },
      displayOrder: 1,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Last Name / Surname',
      fieldKey: 'lastName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Last Name / Surname',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { minLength: 1, maxLength: 50 },
      displayOrder: 2,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'First Name',
      fieldKey: 'firstName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter First Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 3,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Middle Name',
      fieldKey: 'middleName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Middle Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 4,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Name on PAN Card (As per Aadhaar)',
      fieldKey: 'panCardName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter full name as per Aadhaar',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 5,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Date Of Birth / Incorporation',
      fieldKey: 'dob',
      fieldType: ServiceFieldType.DATE,
      placeholder: 'Select Date of Birth',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: null,
      displayOrder: 6,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Gender',
      fieldKey: 'gender',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Gender',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { options: PAN_GENDER_OPTIONS },
      displayOrder: 7,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Single Parent?',
      fieldKey: 'singleParent',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { options: ['Yes', 'No'] },
      displayOrder: 8,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Name to be Printed on PAN Card',
      fieldKey: 'cardNamePrint',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter name to print on PAN',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 9,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Father First Name',
      fieldKey: 'fatherFirstName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Father First Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 10,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Father Middle Name',
      fieldKey: 'fatherMiddleName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Father Middle Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 11,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Father Last Name',
      fieldKey: 'fatherLastName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Father Last Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 12,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Mother First Name',
      fieldKey: 'motherFirstName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Mother First Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 13,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Mother Middle Name',
      fieldKey: 'motherMiddleName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Mother Middle Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 14,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Mother Last Name',
      fieldKey: 'motherLastName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Mother Last Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 15,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Aadhaar Number',
      fieldKey: 'aadhaarNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter 12-digit Aadhaar Number',
      isRequired: true,
      sectionName: 'Aadhaar Details',
      validationRules: { minLength: 12, maxLength: 12, pattern: '^[0-9]{12}$' },
      displayOrder: 16,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Name as per Aadhaar',
      fieldKey: 'aadhaarName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Name exactly as per Aadhaar',
      isRequired: true,
      sectionName: 'Aadhaar Details',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 17,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Mobile Number',
      fieldKey: 'mobileNumber',
      fieldType: ServiceFieldType.MOBILE,
      placeholder: 'Enter 10-digit mobile number',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { pattern: '^[0-9]{10}$' },
      displayOrder: 18,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Email Address',
      fieldKey: 'emailId',
      fieldType: ServiceFieldType.EMAIL,
      placeholder: 'Enter email ID',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: null,
      displayOrder: 19,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Address for Communication',
      fieldKey: 'communicationAddress',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Address for Communication',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { options: ['Residence', 'Office'] },
      displayOrder: 20,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Flat/Room/Door/Block No.',
      fieldKey: 'flatDoorBlock',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Flat/Room/Door/Block No.',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 21,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Building/Village Name',
      fieldKey: 'buildingVillage',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Building/Village Name',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 22,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Road/Street/Lane/Post Office',
      fieldKey: 'roadStreetLane',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Road/Street/Lane/Post Office',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 23,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Area/Locality/Sub-Division',
      fieldKey: 'areaLocality',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Area/Locality/Sub-Division',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 24,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Town/City/District',
      fieldKey: 'townCityDistrict',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Town/City/District',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 25,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'State / Union Territory',
      fieldKey: 'state',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select State',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { options: INDIAN_STATES_OPTIONS },
      displayOrder: 26,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'PIN Code',
      fieldKey: 'pinCode',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter 6-digit PIN Code',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 6, maxLength: 6, pattern: '^[0-9]{6}$' },
      displayOrder: 27,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'AO State',
      fieldKey: 'aoState',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select State',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: { options: INDIAN_STATES_OPTIONS },
      displayOrder: 28,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'AO City',
      fieldKey: 'aoCity',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select City',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 29,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Area Code',
      fieldKey: 'areaCode',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Area Code',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 30,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'AO Type',
      fieldKey: 'aoType',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'AO Type',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 31,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Range Code',
      fieldKey: 'rangeCode',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Range Code',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 32,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'AO Number',
      fieldKey: 'aoNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'AO Number',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 33,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Residential Status',
      fieldKey: 'residentialStatus',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Residential Status',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['Resident', 'Non-Resident'] },
      displayOrder: 34,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Source of Income',
      fieldKey: 'sourceOfIncome',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Source of Income',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['No Income', 'Salary', 'Income from Business or Profession', 'Income from House Property', 'Capital Gains', 'Income from Other sources'] },
      displayOrder: 35,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Proof of Identity',
      fieldKey: 'proofOfIdentity',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Proof of Identity',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['Aadhaar Card', 'Voter ID Card', 'Passport', 'Driving Licence'] },
      displayOrder: 36,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Proof of Address',
      fieldKey: 'proofOfAddress',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Proof of Address',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['Aadhaar Card', 'Voter ID Card', 'Passport', 'Driving Licence', 'Utility Bill'] },
      displayOrder: 37,
    },
    {
      serviceSlug: 'new-pan-apply',
      label: 'Proof of Date of Birth',
      fieldKey: 'proofOfDob',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Proof of Date of Birth',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['Aadhaar Card', 'Birth Certificate', 'Matriculation Certificate', 'Passport'] },
      displayOrder: 38,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 2. PAN Correction
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'pan-correction',
      label: 'Category of Applicant',
      fieldKey: 'applicantCategory',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Category',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { options: ['Individual'] },
      displayOrder: 1,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Existing PAN Number',
      fieldKey: 'panNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter 10-character PAN Number',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { minLength: 10, maxLength: 10, pattern: '^[A-Z]{5}[0-9]{4}[A-Z]{1}$' },
      displayOrder: 2,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Last Name / Surname',
      fieldKey: 'lastName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Last Name / Surname',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { minLength: 1, maxLength: 50 },
      displayOrder: 3,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'First Name',
      fieldKey: 'firstName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter First Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 4,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Middle Name',
      fieldKey: 'middleName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Middle Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 5,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Name on PAN Card (As per Aadhaar)',
      fieldKey: 'panCardName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter full name as per Aadhaar',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 6,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Date Of Birth / Incorporation',
      fieldKey: 'dob',
      fieldType: ServiceFieldType.DATE,
      placeholder: 'Select Date of Birth',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: null,
      displayOrder: 7,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Gender',
      fieldKey: 'gender',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Gender',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { options: PAN_GENDER_OPTIONS },
      displayOrder: 8,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Single Parent?',
      fieldKey: 'singleParent',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { options: ['Yes', 'No'] },
      displayOrder: 9,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Name to be Printed on PAN Card',
      fieldKey: 'cardNamePrint',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter name to print on PAN',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 10,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Father First Name',
      fieldKey: 'fatherFirstName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Father First Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 11,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Father Middle Name',
      fieldKey: 'fatherMiddleName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Father Middle Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 12,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Father Last Name',
      fieldKey: 'fatherLastName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Father Last Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 13,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Mother First Name',
      fieldKey: 'motherFirstName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Mother First Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 14,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Mother Middle Name',
      fieldKey: 'motherMiddleName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Mother Middle Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 15,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Mother Last Name',
      fieldKey: 'motherLastName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Mother Last Name',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: { maxLength: 50 },
      displayOrder: 16,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Fields to Update (Correction Checkboxes)',
      fieldKey: 'fieldsToUpdate',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Comma-separated fields to correct',
      isRequired: true,
      sectionName: 'Personal Info',
      validationRules: null,
      displayOrder: 17,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Existing PAN Details',
      fieldKey: 'existingPanDetails',
      fieldType: ServiceFieldType.TEXTAREA,
      placeholder: 'Enter existing PAN Details',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: null,
      displayOrder: 18,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Correction Reason',
      fieldKey: 'correctionReason',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Reason for correction',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: null,
      displayOrder: 19,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Document Support Details',
      fieldKey: 'documentSupport',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Supporting doc remarks',
      isRequired: false,
      sectionName: 'Personal Info',
      validationRules: null,
      displayOrder: 20,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Aadhaar Number',
      fieldKey: 'aadhaarNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter 12-digit Aadhaar Number',
      isRequired: true,
      sectionName: 'Aadhaar Details',
      validationRules: { minLength: 12, maxLength: 12, pattern: '^[0-9]{12}$' },
      displayOrder: 21,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Name as per Aadhaar',
      fieldKey: 'aadhaarName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Name exactly as per Aadhaar',
      isRequired: true,
      sectionName: 'Aadhaar Details',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 22,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Mobile Number',
      fieldKey: 'mobileNumber',
      fieldType: ServiceFieldType.MOBILE,
      placeholder: 'Enter 10-digit mobile number',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { pattern: '^[0-9]{10}$' },
      displayOrder: 23,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Email Address',
      fieldKey: 'emailId',
      fieldType: ServiceFieldType.EMAIL,
      placeholder: 'Enter email ID',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: null,
      displayOrder: 24,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Address for Communication',
      fieldKey: 'communicationAddress',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Address for Communication',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { options: ['Residence', 'Office'] },
      displayOrder: 25,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Flat/Room/Door/Block No.',
      fieldKey: 'flatDoorBlock',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Flat/Room/Door/Block No.',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 26,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Building/Village Name',
      fieldKey: 'buildingVillage',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Building/Village Name',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 27,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Road/Street/Lane/Post Office',
      fieldKey: 'roadStreetLane',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Road/Street/Lane/Post Office',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 28,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Area/Locality/Sub-Division',
      fieldKey: 'areaLocality',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Area/Locality/Sub-Division',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 29,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Town/City/District',
      fieldKey: 'townCityDistrict',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Town/City/District',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 1, maxLength: 100 },
      displayOrder: 30,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'State / Union Territory',
      fieldKey: 'state',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select State',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { options: INDIAN_STATES_OPTIONS },
      displayOrder: 31,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'PIN Code',
      fieldKey: 'pinCode',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter 6-digit PIN Code',
      isRequired: true,
      sectionName: 'Contact & Address',
      validationRules: { minLength: 6, maxLength: 6, pattern: '^[0-9]{6}$' },
      displayOrder: 32,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'AO State',
      fieldKey: 'aoState',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select State',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: { options: INDIAN_STATES_OPTIONS },
      displayOrder: 33,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'AO City',
      fieldKey: 'aoCity',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select City',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 34,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Area Code',
      fieldKey: 'areaCode',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Area Code',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 35,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'AO Type',
      fieldKey: 'aoType',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'AO Type',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 36,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Range Code',
      fieldKey: 'rangeCode',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Range Code',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 37,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'AO Number',
      fieldKey: 'aoNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'AO Number',
      isRequired: true,
      sectionName: 'AO Code',
      validationRules: null,
      displayOrder: 38,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Residential Status',
      fieldKey: 'residentialStatus',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Residential Status',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['Resident', 'Non-Resident'] },
      displayOrder: 39,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Source of Income',
      fieldKey: 'sourceOfIncome',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Source of Income',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['No Income', 'Salary', 'Income from Business or Profession', 'Income from House Property', 'Capital Gains', 'Income from Other sources'] },
      displayOrder: 40,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Proof of Identity',
      fieldKey: 'proofOfIdentity',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Proof of Identity',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['Aadhaar Card', 'Voter ID Card', 'Passport', 'Driving Licence'] },
      displayOrder: 41,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Proof of Address',
      fieldKey: 'proofOfAddress',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Proof of Address',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['Aadhaar Card', 'Voter ID Card', 'Passport', 'Driving Licence', 'Utility Bill'] },
      displayOrder: 42,
    },
    {
      serviceSlug: 'pan-correction',
      label: 'Proof of Date of Birth',
      fieldKey: 'proofOfDob',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select Proof of Date of Birth',
      isRequired: true,
      sectionName: 'Documents',
      validationRules: { options: ['Aadhaar Card', 'Birth Certificate', 'Matriculation Certificate', 'Passport'] },
      displayOrder: 43,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 3. PAN Find
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'pan-find',
      label: 'Aadhaar Number',
      fieldKey: 'aadhaarNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter 12-digit Aadhaar Number',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: { minLength: 12, maxLength: 12, pattern: '^[0-9]{12}$' },
      displayOrder: 1,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 4. PAN PDF Service
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'pan-pdf-service',
      label: 'Aadhaar Number',
      fieldKey: 'aadhaarNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter 12-digit Aadhaar Number',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: { minLength: 12, maxLength: 12, pattern: '^[0-9]{12}$' },
      displayOrder: 1,
    },
    {
      serviceSlug: 'pan-pdf-service',
      label: 'PAN Number',
      fieldKey: 'panNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter 10-character PAN Number',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: { minLength: 10, maxLength: 10, pattern: '^[A-Z]{5}[0-9]{4}[A-Z]{1}$' },
      displayOrder: 2,
    },
    {
      serviceSlug: 'pan-pdf-service',
      label: 'Date Of Birth',
      fieldKey: 'dob',
      fieldType: ServiceFieldType.DATE,
      placeholder: 'Select Date of Birth',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: null,
      displayOrder: 3,
    },
    {
      serviceSlug: 'pan-pdf-service',
      label: 'Aadhaar OTP Call Number',
      fieldKey: 'aadhaarOtpCallNumber',
      fieldType: ServiceFieldType.MOBILE,
      placeholder: 'Enter mobile number for Aadhaar OTP',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: { pattern: '^[0-9]{10}$' },
      displayOrder: 4,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 5. Voter PDF
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'voter-pdf',
      label: 'EPIC Number',
      fieldKey: 'epicNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter EPIC (Voter Card) Number',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: { pattern: '^[A-Z]{3}[0-9]{7}$' },
      displayOrder: 1,
    },
    {
      serviceSlug: 'voter-pdf',
      label: 'State Name',
      fieldKey: 'stateName',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select State',
      isRequired: true,
      sectionName: 'Application Details',
      validationRules: { options: INDIAN_STATES_OPTIONS },
      displayOrder: 2,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 6. Voter Mobile Number Link
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'voter-mobile-number-link',
      label: 'EPIC Number',
      fieldKey: 'epicNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter EPIC Number',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: { pattern: '^[A-Z]{3}[0-9]{7}$' },
      displayOrder: 1,
    },
    {
      serviceSlug: 'voter-mobile-number-link',
      label: 'Mobile Number',
      fieldKey: 'mobileNumber',
      fieldType: ServiceFieldType.MOBILE,
      placeholder: 'Enter 10-digit Mobile Number',
      isRequired: true,
      sectionName: 'Contact Details',
      validationRules: { pattern: '^[0-9]{10}$' },
      displayOrder: 2,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 7. Samagra PDF
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'samagra-pdf',
      label: 'Member ID / Family ID',
      fieldKey: 'memberOrFamilyId',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Member ID or Family ID',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: null,
      displayOrder: 1,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 8. Member Approval
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'member-approval',
      label: 'Request ID',
      fieldKey: 'requestId',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Request ID',
      isRequired: true,
      sectionName: 'Application Details',
      validationRules: null,
      displayOrder: 1,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 9. Nihar Se Sasural Transfer
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'nihar-se-sasural-transfer',
      label: 'Husband Name',
      fieldKey: 'husbandName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Husband Name',
      isRequired: true,
      sectionName: 'Applicant Details',
      validationRules: null,
      displayOrder: 1,
    },
    {
      serviceSlug: 'nihar-se-sasural-transfer',
      label: 'Husband Member ID',
      fieldKey: 'husbandMemberId',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Husband Samagra Member ID',
      isRequired: true,
      sectionName: 'Applicant Details',
      validationRules: { minLength: 9, maxLength: 9, pattern: '^[0-9]{9}$' },
      displayOrder: 2,
    },
    {
      serviceSlug: 'nihar-se-sasural-transfer',
      label: 'Wife Name',
      fieldKey: 'wifeName',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Wife Name',
      isRequired: true,
      sectionName: 'Applicant Details',
      validationRules: null,
      displayOrder: 3,
    },
    {
      serviceSlug: 'nihar-se-sasural-transfer',
      label: 'Wife Member ID',
      fieldKey: 'wifeMemberId',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Wife Samagra Member ID',
      isRequired: true,
      sectionName: 'Applicant Details',
      validationRules: { minLength: 9, maxLength: 9, pattern: '^[0-9]{9}$' },
      displayOrder: 4,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 10. Family Approval
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'family-approval',
      label: 'Request ID',
      fieldKey: 'requestId',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Request ID',
      isRequired: true,
      sectionName: 'Application Details',
      validationRules: null,
      displayOrder: 1,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 11. RC PDF
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'rc-pdf',
      label: 'Vehicle Number',
      fieldKey: 'vehicleNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Vehicle Number (e.g. MP04CC1234)',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: { pattern: '^[A-Z]{2}[0-9]{2}[A-Z]{1,2}[0-9]{4}$' },
      displayOrder: 1,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 12. DL PDF
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'dl-pdf',
      label: 'Driving Licence Number',
      fieldKey: 'licenceNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter Driving Licence Number (e.g. MP0420190001234)',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: { pattern: '^[A-Z]{2}[0-9]{2}[0-9]{11}$' },
      displayOrder: 1,
    },
    {
      serviceSlug: 'dl-pdf',
      label: 'Date Of Birth',
      fieldKey: 'dob',
      fieldType: ServiceFieldType.DATE,
      placeholder: 'Select Date of Birth',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: null,
      displayOrder: 2,
    },

    // ──────────────────────────────────────────────────────────────────────────
    // 13. Farmer PDF
    // ──────────────────────────────────────────────────────────────────────────
    {
      serviceSlug: 'farmer-pdf',
      label: 'Aadhaar Number',
      fieldKey: 'aadhaarNumber',
      fieldType: ServiceFieldType.TEXT,
      placeholder: 'Enter 12-digit Aadhaar Number',
      isRequired: true,
      sectionName: 'Identity Details',
      validationRules: { minLength: 12, maxLength: 12, pattern: '^[0-9]{12}$' },
      displayOrder: 1,
    },
    {
      serviceSlug: 'farmer-pdf',
      label: 'State Name',
      fieldKey: 'stateName',
      fieldType: ServiceFieldType.SELECT,
      placeholder: 'Select State',
      isRequired: true,
      sectionName: 'Application Details',
      validationRules: { options: INDIAN_STATES_OPTIONS },
      displayOrder: 2,
    },
  ];

  console.log('🧹 Cleaning up old service field configurations...');

  const activeFieldsSet = new Set<string>();
  const serviceSlugToIdMap = new Map<string, string>();

  for (const f of fields) {
    let serviceId = serviceSlugToIdMap.get(f.serviceSlug);
    if (!serviceId) {
      const service = await prisma.service.findUnique({ where: { slug: f.serviceSlug } });
      if (service) {
        serviceId = service.id;
        serviceSlugToIdMap.set(f.serviceSlug, service.id);
      }
    }
    if (serviceId) {
      activeFieldsSet.add(`${serviceId}:${f.fieldKey}`);
    }
  }

  const existingFields = await prisma.serviceField.findMany();
  for (const f of existingFields) {
    const key = `${f.serviceId}:${f.fieldKey}`;
    if (!activeFieldsSet.has(key)) {
      await prisma.serviceField.delete({ where: { id: f.id } });
    }
  }

  let seededCount = 0;

  for (const f of fields) {
    const service = await prisma.service.findUnique({ where: { slug: f.serviceSlug } });
    if (!service) {
      throw new Error(`Service with slug "${f.serviceSlug}" not found during fields seeding.`);
    }

    const rules = f.validationRules !== null ? f.validationRules : undefined;

    await prisma.serviceField.upsert({
      where: {
        serviceId_fieldKey: {
          serviceId: service.id,
          fieldKey: f.fieldKey,
        },
      },
      update: {
        label: f.label,
        fieldType: f.fieldType,
        placeholder: f.placeholder,
        isRequired: f.isRequired,
        validationRules: rules,
        sectionName: f.sectionName ?? null,
        displayOrder: f.displayOrder,
      },
      create: {
        serviceId: service.id,
        fieldKey: f.fieldKey,
        label: f.label,
        fieldType: f.fieldType,
        placeholder: f.placeholder,
        isRequired: f.isRequired,
        validationRules: rules,
        sectionName: f.sectionName ?? null,
        displayOrder: f.displayOrder,
      },
    });
    seededCount++;
  }

  return seededCount;
}
