import { env } from './env';

export const RECHARGE_CONFIG = {
  MIN_TOPUP_AMOUNT_PAISE: 100, // ₹100
  MAX_TOPUP_AMOUNT_PAISE: 2500000, // ₹25,000
  PAYMENT_EXPIRY_MINUTES: 15,
  UTR_SUBMISSION_GRACE_HOURS: 24,
  MAX_RESUBMISSION_LIMIT: env.MAX_RESUBMISSION_LIMIT,
  UPI_ACCOUNT_ID: env.UPI_ACCOUNT_ID,
  UPI_VPA: env.UPI_VPA,
  UPI_PAYEE_NAME: env.UPI_PAYEE_NAME,
  UPI_NOTE_PREFIX: env.UPI_NOTE_PREFIX,
};
